hvanbakel/CsprojToVs2017

- Project2015To2017/AssemblyReferenceTransformation.cs
- Project2015To2017/Definition/Project.cs
- Project2015To2017/Program.cs
- Project2015To2017/Writing/ProjectWriter.cs
- Project2015To2017Tests/AssemblyReferenceTransformationTest.cs
If your project file previously had extra assemblies added - e.g. `System.configuration`, then this was missing after converting the project file.
It appears some assemblies are included by default even when not specified, so I filtered them out.
> Convert non default assembly references as well.

- Project2015To2017/Writing/ProjectWriter.cs
A normal (old) project also includes `AssemblyFileVersion` and `AssemblyConfiguration` in `AssemblyInfo.cs`. I was getting a duplicated attribute compile error.
This fixes it.
> Add missing generate assembly attribute property group elements

- Project2015To2017/ProjectPropertiesTransformation.cs
- Project2015To2017Tests/ProjectPropertiesTransformationTest.cs
The values of Optimize, TreatWarningsAsErrors, AllowUnsafeBlocks, DefineConstants, RootNamespace and AssemblyName were not found even though they existed in csproj file. It was missing the namespace.
> Fix parsing of project properties.

- Project2015To2017/Program.cs
- Project2015To2017/Writing/ProjectWriter.cs
It is not required to have `RootNamespace` and `AssemblyName` if they are the same as the csproj filename.
This suppresses them in that situation.
> Don't convert RootNamespace and AssemblyName if same as project name

- Project2015To2017/Writing/ProjectWriter.cs
I found that when you change properties of a converted project using Visual Studio UI or using "Edit xxx.csproj", then it re-added a UTF-8 BOM that was removed during conversion.
> Use UTF8 encoding for project file

- Project2015To2017/Config.cs
- Project2015To2017/FileTransformation.cs
- Project2015To2017/Program.cs
- Project2015To2017/ProjectPropertiesTransformation.cs
- Project2015To2017/Writing/ProjectWriter.cs
Avoid double assemblyinfo attributes,
use 'Version' instead of PackageVersion,
always update compile items (as compile files are include automatic, update is need to avoid double inclusion error),
remove .nuspec from project
> Small fixes for encountered problems

- .gitattributes
Some files have inconsistent line endings causing warnings when opening. Adding this default .gitattributes should stop it happening with future changes. A separate pull request may come with fixes to the existing files
> Adding default .gitattributes to resolve line ending warnings in VS

- Project2015To2017/Project2015To2017.csproj
- Project2015To2017/RemovePackageAssemblyReferencesTransformation.cs
- Project2015To2017Tests/Project2015To2017Tests.csproj
- Project2015To2017Tests/ProjectReferenceTransformationTest.cs
- Project2015To2017Tests/RemovePackageAssemblyReferencesTransformationTest.cs
- Project2015To2017Tests/TestFiles/AltNugetConfig/ProjectFolder/net46console.testcsproj
- Project2015To2017Tests/TestFiles/AltNugetConfig/ProjectFolder/packages.config
- Project2015To2017Tests/TestFiles/AltNugetConfig/nuget.config
The deleting of assembly references that are catered for by PackageReference style packages is now extended to support a different packages folder being specified in nuget.config.
Fixes #61
> Add support for alternative folder for extracted packages

- Project2015To2017/Program.cs
Logic error is causing it to think projects are directories and vice versa
> Fix .csproj and directory processing regression

- Project2015To2017/Definition/Project.cs
- Project2015To2017/Project2015To2017.csproj
- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Transforms/Helpers.cs
- Project2015To2017/Transforms/RemovePackageAssemblyReferencesTransformation.cs
- Project2015To2017/Transforms/RemovePackageImportsTransformation.cs
- Project2015To2017Tests/Project2015To2017Tests.csproj
- Project2015To2017Tests/RemovePackageAssemblyReferencesTransformationTest.cs
- Project2015To2017Tests/TestFiles/AltNugetConfig/ProjectFolder/net46console.testcsproj
- Project2015To2017Tests/TestFiles/AltNugetConfig/ProjectFolder/packages.config
These are imported at build time so don't need to be in the final project.
The check I added for the targets is quite conservative, looking for a specific set of properties as per the ones auto-generated by nuget.
I updated the nuget packages being used because I thought I was hitting a bug with ms test. Turns out it was actually DropBox causing my problem. Let me know if you would like me to roll back those updates.
I also pulled the nuget packages folder into the project as a property because I needed to re-use it for the new transformation.
Fixes #66
> Remove props and targets that come from packages

- Project2015To2017/Transforms/FileTransformation.cs
Spotted this one while working on another fix.
Make sure that files starting with 'Obj' don't get picked up by the check for the obj folder.
> Allow for files called \ObjSomething.xyz

- Project2015To2017/Reading/NuSpecReader.cs
- Project2015To2017/Transforms/NugetPackageTransformation.cs
I had a problem where nuspecs were getting picked up from solutions in sub-folders and from the backup folder when I had previously run the transform and then reverted it. 
In our case the nuspec is always at the root of the project and I think this is a safe assumption.
> Nuspec in top directory only

- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017Tests/FileTransformationTest.cs
- Project2015To2017Tests/TestFiles/FileInclusion/fileinclusion.testcsproj
- Project2015To2017Tests/TestFiles/OtherTestProjects/OtherTestClass.cs
Compile Includes with a Link are usually from an other directory, so they have to end as an Include and not as an Update.
fixes #128
> Keep Linked Files as an Include

- Project2015To2017/Definition/Project.cs
- Project2015To2017/Reading/AssemblyInfoReader.cs
- Project2015To2017/Transforms/AssemblyAttributeTransformation.cs
- Project2015To2017/Transforms/AssemblyReferenceTransformation.cs
- Project2015To2017/Writing/ProjectWriter.cs
- Project2015To2017Tests/AssemblyAttributeTransformationTest.cs
- Project2015To2017Tests/AssemblyReferenceTransformationTest.cs
* Do not allow generated AssemblyInfo in case more that 1 AssemblyInfo file is found
* Add Project.HasMultipleAssemblyInfos flag
* Add test to ensure GenerateAssemblyInfo is set to false correctly
* Do not remove Microsoft.CSharp assembly reference (#40 is wrong, it is still needed)
* Update tests to reflect changes
* Minor formatting fixes
> Minor improvements

- Project2015To2017/Definition/Project.cs
- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Reading/ProjectReader.cs
- Project2015To2017/Transforms/XamlPagesTransformation.cs
- Project2015To2017/UnsupportedProjectTypes.cs
- Project2015To2017/Writing/ProjectWriter.cs
- Project2015To2017Tests/UnsupportedProjectTypesTest.cs
* Detect WPF, Windows Forms, UWP and Xamarin (last 2 are disabled until simplification PR is merged)
* Remove newly detected project types from list of unsupported ones
* Add XamlPagesTransformation to prevent duplicated item inclusion (Page & ApplicationDefinition, handled by MSBuild.Sdk.Extras)
* Add MSBuild.Sdk.Extras SDK usage to ProjectWriter
* Add IsWindowsFormsProject & IsWindowsPresentationFoundationProject to Project model
XamlTransformationTest.cs was originally part of this commit, removed due to dependency on simplification PR. Will be pushed as soon as simplification PR is merged, either in this or separate PR.
> Enable WPF, Windows Forms, UAP/UWP and Xamarin conversion

- Project2015To2017.Console/Program.cs
- Project2015To2017/Analysis/Analyzer.cs
- Project2015To2017/Analysis/ConsoleReporter.cs
- Project2015To2017/Analysis/ConsoleReporterOptions.cs
- Project2015To2017/Analysis/DiagnosticBase.cs
- Project2015To2017/Analysis/DiagnosticLocation.cs
- Project2015To2017/Analysis/DiagnosticResult.cs
- Project2015To2017/Analysis/Diagnostics/W001IllegalProjectTypeDiagnostic.cs
- Project2015To2017/Analysis/Diagnostics/W010ConfigurationsMismatchDiagnostic.cs
- Project2015To2017/Analysis/Diagnostics/W020MicrosoftCSharpDiagnostic.cs
- Project2015To2017/Analysis/ExtensionMethods.cs
- Project2015To2017/Analysis/IDiagnosticLocation.cs
- Project2015To2017/Analysis/IDiagnosticResult.cs
- Project2015To2017/Analysis/IReporter.cs
- Project2015To2017/Analysis/IReporterOptions.cs
- Project2015To2017/Analysis/ReporterBase.cs
- Project2015To2017/Analysis/ReporterOptions.cs
* Make `IReporter` and `ReporterBase` generic with `IReporterOptions` type generic parameter
* Make `Analyzer` generic with `TReporter` and `TReporterOptions` generic parameters
* `Analyzer` requests `IReporter` to create suitable options for given project
* `ReporterOptions` -> `ConsoleReporterOptions` (each `IReporter` has its own options)
* Add copy constructors to `DiagnosticResult` & `DiagnosticLocation` (no deep cloning)
* Move `DiagnosticLocation` `XElement` line information assignment to extension method
* Add `Project` property to `DiagnosticResult`
* Add `SourcePath` property to `DiagnosticLocation` that stores human-readable relative path
* Add `GetSourcePath` extension method to retrieve `SourcePath` or default value
> Real Reporter extensibility

- Project2015To2017/Definition/AssemblyReference.cs
- Project2015To2017/Definition/IOriginatedReference.cs
- Project2015To2017/Definition/PackageReference.cs
- Project2015To2017/Definition/Project.cs
- Project2015To2017/Definition/ProjectReference.cs
- Project2015To2017/Reading/AssemblyInfoReader.cs
- Project2015To2017/Reading/ProjectReader.cs
- Project2015To2017/Transforms/AssemblyReferenceTransformation.cs
- Project2015To2017/Transforms/DefaultAssemblyReferenceRemovalTransformation.cs
- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017/Transforms/Helpers.cs
- Project2015To2017/Transforms/PackageReferenceTransformation.cs
- Project2015To2017/Transforms/RemovePackageAssemblyReferencesTransformation.cs
- Project2015To2017/Transforms/XamlPagesTransformation.cs
- Project2015To2017/Writing/ProjectWriter.cs
- Project2015To2017Tests/FileTransformationTest.cs
- Project2015To2017Tests/XamlTransformationTest.cs
* Rename `IncludeItems` to `ItemGroups`
* Add `IOriginatedReference` for locating the origin of the reference in XML document
* `AssemblyReference`, `PackageReference` and `ProjectReference` implement `IOriginatedReference`
* Seal more classes in `Project2015To2017.Definition` namespace
* Adapt all code to the changes above
* Update `SdkExtrasVersion` to `MSBuild.Sdk.Extras/1.6.46`
* Preserve original XML elements location as much as possible in `ProjectWriter`
* Huge refactoring of `FileTransformation`, preserve original structure as much as possible
* Reduce `FileTransformation` noise in the output log
* Adapt tests to the changes
Fixes #151.
> Complete refactoring of IncludeItems

- Project2015To2017.Console/Program.cs
- Project2015To2017/Definition/Project.cs
- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Reading/ProjectPropertiesReader.cs
- Project2015To2017/Reading/ProjectReader.cs
- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017/Transforms/Helpers.cs
- Project2015To2017/Transforms/PrimaryUnconditionalPropertyTransformation.cs
- Project2015To2017/Transforms/PropertyDeduplicationTransformation.cs
- Project2015To2017/Transforms/PropertySimplificationTransformation.cs
- Project2015To2017/Writing/ProjectWriter.cs
- Project2015To2017Tests/FileTransformationTest.cs
- Project2015To2017Tests/PrimaryUnconditionalPropertyTransformationTest.cs
- Project2015To2017Tests/ProjectPropertiesReadTest.cs
- Project2015To2017Tests/ProjectWriterTest.cs
- Project2015To2017Tests/PropertySimplificationTransformationTest.cs
- Project2015To2017Tests/XamlTransformationTest.cs
* Add `PrimaryPropertyGroup` property to `Project` model (stores the only unconditional `PropertyGroup`)
* Add `PrimaryUnconditionalPropertyTransformation` that takes care of the properties in unconditional `PropertyGroup`.
* Move primary property group logic to the newly created transformation
* Try harder at preserving original XML structure
* Make `ProjectPropertiesReader` non-static (like other readers), initialized with logger
* Remove unneeded arguments (like `XElement` when `Definition.Project` is already a parameter)
* Improve `FileTransformation` to be more correct
* Update `SdkExtrasVersion` to `MSBuild.Sdk.Extras/1.6.47`
* Reduce code duplication by moving helpers to Helpers (a surprise for sure, but a welcome one)
* Refactor `PropertySimplificationTransformation` to simplify …
> Refactoring of PropertyGroups and bugfixes

- Project2015To2017/Definition/AssemblyAttributes.cs
- Project2015To2017/Transforms/AssemblyAttributeTransformation.cs
- Project2015To2017Tests/AssemblyAttributeTransformationTest.cs
This clears up the following attributes if they are blank:
```csharp
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
```
It also pulls the `NeutralLanguage` attribute across into the project file if it is present
Fixes #166
> More assembly info filtering

- Project2015To2017/Analysis/Diagnostics/W001IllegalProjectTypeDiagnostic.cs
- Project2015To2017/Analysis/Diagnostics/W010ConfigurationsMismatchDiagnostic.cs
- Project2015To2017/Analysis/Diagnostics/W034ReferenceAliasesDiagnostic.cs
- Project2015To2017/Definition/Project.cs
- Project2015To2017/Definition/ProjectReference.cs
- Project2015To2017/Extensions.cs
- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Reading/AssemblyInfoReader.cs
- Project2015To2017/Reading/ConditionEvaluator.cs
- Project2015To2017/Reading/ProjectPropertiesReader.cs
- Project2015To2017/Reading/ProjectReader.cs
- Project2015To2017/Reading/SolutionReader.cs
- Project2015To2017/Transforms/EmptyGroupRemoveTransformation.cs
- Project2015To2017/Transforms/NuGetPackageTransformation.cs
- Project2015To2017/Transforms/PrimaryUnconditionalPropertyTransformation.cs
- Project2015To2017/Transforms/PropertySimplificationTransformation.cs
- Project2015To2017/Transforms/TargetFrameworkTransformation.cs
- Project2015To2017Tests/NuGetPackageTransformationTest.cs
- Project2015To2017Tests/ProjectPropertiesReadTest.cs
- Project2015To2017Tests/PropertySimplificationTransformationTest.cs
- Project2015To2017Tests/W001IllegalProjectTypeDiagnosticTest.cs
* API removal: Remove `RootNamespace` and `AssemblyName` properties from model (it was RC right? one tiny change)
* Extended `ProjectReference` model (and added filling new properties to both `SolutionReader` and `ProjectReader`)
* Use new APIs in diagnostics W001, W010, W034
* Fix AssemblyInfo detection when file is missing (e.g. generated during build from template)
* Extend `ConditionEvaluator` APIs to allow more efficient queries
* Recreate relative path fix set for Unix-like OS closely based on MSBuild sources (works only on non-Windows platforms)
* Rewrite `SolutionReader` to use MSBuild routine for parsing _Project_ definition lines
* Add `EmptyGroupRemoveTransformation` (obvious designation, fixes regression in one of my latest PRs)
* Greatly improve property simplification per …
> Last bit of fixes before 2.0 release

- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Transforms/AssemblyAttributeTransformation.cs
- Project2015To2017/Transforms/AssemblyReferenceTransformation.cs
- Project2015To2017/Transforms/DefaultAssemblyReferenceRemovalTransformation.cs
- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017/Transforms/ITransformation.cs
- Project2015To2017/Transforms/NuGetPackageTransformation.cs
- Project2015To2017/Transforms/PrimaryUnconditionalPropertyTransformation.cs
- Project2015To2017/Transforms/PropertyDeduplicationTransformation.cs
- Project2015To2017/Transforms/PropertySimplificationTransformation.cs
- Project2015To2017/Transforms/RemovePackageAssemblyReferencesTransformation.cs
- Project2015To2017/Transforms/RemovePackageImportsTransformation.cs
- Project2015To2017/Transforms/TargetFrameworkTransformation.cs
- Project2015To2017/Transforms/TestProjectPackageReferenceTransformation.cs
- Project2015To2017/Transforms/XamlPagesTransformation.cs
- Project2015To2017Tests/AssemblyAttributeTransformationTest.cs
- Project2015To2017Tests/AssemblyReferenceTransformationTest.cs
- Project2015To2017Tests/DefaultAssemblyReferenceRemovalTransformationTest.cs
- Project2015To2017Tests/FileTransformationTest.cs
- Project2015To2017Tests/NuGetPackageTransformationTest.cs
- Project2015To2017Tests/PrimaryUnconditionalPropertyTransformationTest.cs
- Project2015To2017Tests/PropertySimplificationTransformationTest.cs
- Project2015To2017Tests/RemovePackageAssemblyReferencesTransformationTest.cs
- Project2015To2017Tests/TargetFrameworkTransformationTest.cs
- Project2015To2017Tests/TestProjectPackageReferenceTransformationTest.cs
- Project2015To2017Tests/XamlTransformationTest.cs
Putting `ILogger` as a parameter on the `ITransformation` call never really made sense to me so now that's refactored. Since that's a change to the public API it would need to go in prior to 2.0 non RC.
> Refactored ITransformation to not include logger for 2.0

- Project2015To2017/Writing/ProjectWriter.cs
- Project2015To2017Tests/ProjectPropertiesReadTest.cs
- Project2015To2017Tests/ProjectWriterTest.cs
- Project2015To2017Tests/PropertySimplificationTransformationTest.cs
- Project2015To2017Tests/XamlTransformationTest.cs
A while back in PR #17 the files were written out as UTF-8 which is the default.
The file writing process was changed from a streamwriter with UTF-8 encoding over to File.WriteAllText but UTF-8 seems to have been dropped so this PR adds it back.
> Convert all file writes to output as UTF-8

- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Transforms/AssemblyAttributeTransformation.cs
- Project2015To2017/Transforms/AssemblyFilterDefaultTransformation.cs
- Project2015To2017/Transforms/AssemblyFilterHintedPackageReferencesTransformation.cs
- Project2015To2017/Transforms/AssemblyFilterPackageReferencesTransformation.cs
- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017/Transforms/ILegacyOnlyProjectTransformation.cs
- Project2015To2017/Transforms/IModernOnlyProjectTransformation.cs
- Project2015To2017/Transforms/ITransformation.cs
- Project2015To2017/Transforms/ImportsTargetsFilterPackageReferencesTransformation.cs
- Project2015To2017/Transforms/NuGetPackageTransformation.cs
- Project2015To2017/Transforms/PrimaryProjectPropertiesUpdateTransformation.cs
- Project2015To2017/Transforms/PropertySimplificationTransformation.cs
- Project2015To2017/Transforms/TargetFrameworkReplaceTransformation.cs
- Project2015To2017/Transforms/TestProjectPackageReferenceTransformation.cs
- Project2015To2017/Transforms/XamlPagesTransformation.cs
- Project2015To2017Tests/AssemblyFilterDefaultTransformationTest.cs
- Project2015To2017Tests/AssemblyFilterHintedPackageReferencesTransformationTest.cs
- Project2015To2017Tests/AssemblyFilterPackageReferencesTransformationTest.cs
- Project2015To2017Tests/ImportsTargetsFilterPackageReferencesTransformationTest.cs
- Project2015To2017Tests/PrimaryProjectPropertiesUpdateTransformationTest.cs
- Project2015To2017Tests/TargetFrameworkReplaceTransformationTest.cs
* Rename transformations for consistency
* Add `ILegacyOnlyProjectTransformation` and `IModernOnlyProjectTransformation` for future PR
* Rename transformation tests to match
* Move one test to its own `ImportsTargetsFilterPackageReferencesTransformationTest` file
* Remove unused using statements
> Rename transformations for consistency

- Project2015To2017.Console/Program.cs
- Project2015To2017.Migrate2017.Tool/CommandLogic.cs
- Project2015To2017.Migrate2017.Tool/Program.cs
- Project2015To2017.Migrate2017.Tool/Project2015To2017.Migrate2017.Tool.csproj
- Project2015To2017.sln.DotSettings
- Project2015To2017/ConversionOptions.cs
- Project2015To2017/Definition/Solution.cs
- Project2015To2017/ProjectConverter.cs
- Project2015To2017/Reading/ConditionEvaluator.cs
- Project2015To2017/Reading/NuSpecReader.cs
- Project2015To2017/Reading/ProjectPropertiesReader.cs
- Project2015To2017/Reading/ProjectReader.cs
- Project2015To2017/Reading/SolutionReader.cs
- Project2015To2017/Transforms/AssemblyAttributeTransformation.cs
- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017/Transforms/PropertySimplificationTransformation.cs
- Project2015To2017/Transforms/TestProjectPackageReferenceTransformation.cs
- Project2015To2017/Transforms/XamlPagesTransformation.cs
- Project2015To2017Tests/AssemblyAttributeTransformationTest.cs
- Project2015To2017Tests/SolutionReaderTests.cs
* Make specialized `ProjectConverter` methods public
* Rewrite projects selection logic from scratch for modern CLI tool
* Add globbing as a fallback to modern CLI tool
* Reduce default log verbosity (mark common messages as _Debug_ instead of _Informational_)
* Add Trace level logging to modern CLI tool
* Make evaluate command use only _W00x_ and _W01x_ analyzer diagnostic sets
* Print unsupported solution projects in evaluate command
* Add `--force-transformations` CLI option
* Make `ConditionEvaluator` much safer against unknown conditionals
* Revert `<SolutionDir />` removal from `PropertySimplificationTransformation` (it is not the default in CPS, used when running MSBuild on single project instead of solution). Refer to #165.
* Fix NuGet name case in log messages
* Use `FileInfo` as …
> Improve CLI, fix bugs

- Project2015To2017/Transforms/FileTransformation.cs
- Project2015To2017Tests/FileTransformationTest.cs
- Project2015To2017Tests/Project2015To2017Tests.csproj
- Project2015To2017Tests/TestFiles/FileInclusion/fileExclusion.testcsproj
It's not pretty because of the wildcard support we currently have. But if the user is not using a wildcard include then we can generate the appropriate exclusions. Having a wildcard include is probably an exception anyway as it was never really supported in any UI and the current wildcard include is automatic.
> Exclude files when previously excluded and no wildcards are in play

- Project2015To2017.Core/Analysis/Diagnostics/W001IllegalProjectTypeDiagnostic.cs
- Project2015To2017.Core/Analysis/Diagnostics/W011UnsupportedConditionalDiagnostic.cs
- Project2015To2017.Core/Definition/Project.cs
- Project2015To2017.Core/Definition/ProjectExtensions.cs
- Project2015To2017.Core/Extensions.cs
- Project2015To2017.Core/Reading/ProjectPropertiesReader.cs
- Project2015To2017.Core/Reading/ProjectReader.cs
- Project2015To2017.Core/Transforms/PrimaryProjectPropertiesUpdateTransformation.cs
- Project2015To2017.Core/UnsupportedProjectTypes.cs
- Project2015To2017.Core/Writing/ProjectWriter.cs
- Project2015To2017.Migrate2017.Library/Transforms/BrokenHookTargetsTransformation.cs
- Project2015To2017.Migrate2017.Library/Transforms/FileTransformation.cs
- Project2015To2017.Migrate2017.Library/Transforms/FrameworkReferencesTransformation.cs
- Project2015To2017.Migrate2017.Library/Transforms/ImportsTargetsFilterPackageReferencesTransformation.cs
- Project2015To2017.Migrate2017.Library/Transforms/XamlPagesTransformation.cs
- Project2015To2017.Migrate2017.Library/Vs15TransformationSet.cs
- Project2015To2017.Tests/Project2015To2017.Tests.csproj
- Project2015To2017.Tests/PropertySimplificationTransformationTest.cs
- Project2015To2017.Tests/UnsupportedProjectTypesTest.cs
- Project2015To2017.Tests/XamlTransformationTest.cs
- Project2015To2017/Facility.cs
* Add listing of already converted projects to evaluate CLI command
* Use Guid as keys in Dictionary where possible (always correctly ignores casing, improves performance)
* Replace IsWindowsFormsProject and IsWindowsPresentationFoundationProject fields with extension methods (preparation for .NET Core 3)
* Refactor project SDK assignment method (no more hacks in ProjectWriter)
* Add IterateProjectTypeGuids helper extension method
* Refactor out HandleSpecialProjectTypes into FrameworkReferencesTransformation (more robust this way)
* Add BrokenHookTargetsTransformation (fixes #172)
* Improve FileTransformation to fix recently arisen issues (tested on Dopamine, fixes #210)
* Fix ImportsTargetsFilterPackageReferencesTransformation to support multiple `<Error />` from different NuGet …
> A variety of fixes

- Project2015To2017.Migrate2017.Library/Transforms/FileTransformation.cs
Hi, 
first off thank you for this great tool. I stumpled upon a minor problem for my migrated projects.
I am using linked app.configs in my test scenarios, so that i can reuse configuration, but after migrating them they are gone and i have to reconfigure them.
Why are *.config-Files skipped? I found this issue #155 but i do not understand why this is a problem.
> Keep linked app.config

- Project2015To2017.Core/Writing/ProjectWriter.cs
Hi,
Some of PackageReference references in our project don't have a Version specified so the conversion crashes with the following exception:
> System.ArgumentNullException: Value cannot be null.
> Parameter name: value
>    at new System.Xml.Linq.XAttribute(XName name, object value)
>    at XElement Project2015To2017.Writing.ProjectWriter.CreateXml(Project project) in CsprojToVs2017\Project2015To2017.Core\Writing\ProjectWriter.cs:line 252
>    at bool Project2015To2017.Writing.ProjectWriter.WriteProjectFile(Project project) in CsprojToVs2017\Project2015To2017.Core\Writing\ProjectWriter.cs:line 75
>    at bool Project2015To2017.Writing.ProjectWriter.TryWriteOrThrow(Project project, bool makeBackups) CsprojToVs2017\Project2015To2017.Core\Writing\ProjectWriter.cs:line 57
>    at bool …
> Don't crash if PackageReference had no Version information

- Project2015To2017.Core/Definition/AssemblyAttributes.cs
- Project2015To2017.Tests/TestFiles/Solutions/ClassLibrary/Properties/AssemblyInfo.cs
Also updated ```TestFiles/Solutions/ClassLibrary/Properties/AssemblyInfo.cs```, however I did not find a test where this is used...
> Fix #260: Crash when project contains NeutralResourcesLanguage attribute
